packages:
    - "examples/**/*"
    - "packages/router"

catalog:
    match-sorter: ^8.1.0
    sort-by: ^1.2.0

catalogs:
    remix:
        "@remix-run/dom": jam
        "@remix-run/events": jam
        "@remix-run/style": jam
        "@remix-run/library": jam
        "@remix-run/fetch-router": latest
        "@remix-run/file-storage": latest
        "@remix-run/headers": latest
        "@remix-run/lazy-file": latest
        "@remix-run/node-fetch-server": latest
        "@remix-run/route-pattern": latest
        "@remix-run/html-template": latest
        "@remix-run/router": ^1.23.0
    crank:
        "@b9g/crank": ^0.7.2
    std:
        "@std/assert": jsr:^1.0.15
        "@std/async": jsr:^1.0.15
    dev:
        vite: npm:rolldown-vite@latest
        tsdown: ^0.15.7
    tools:
        "@biomejs/biome": ^2.3.0
        "@typescript/native-preview": latest
        "prettier": ^3.6.2

overrides:
    vite: npm:rolldown-vite@latest

onlyBuiltDependencies:
    - esbuild
    - sharp
    - unrs-resolver
